services:
    select_backend:
      container_name: select_ms
      build: .
      volumes:
        - .:/app
      expose:
        - 9000
      networks:
        - select

    nginx:
      image: nginx:stable-alpine
      container_name: select_ms_nginx
      ports:
        - "8077:80"
      volumes:
        - .:/app
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - select_backend
      networks:
        - select

    select_db:
      container_name: select_ms_db
      image: mysql:8
      restart: always
      environment:
        MYSQL_DATABASE: check
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
      ports:
        - 33066:3306
      networks:
        - select

networks:
  select:
    name: select
